### ISSUE TITLE
update to later version of codec package

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/codec_data_explorer#11]
... now that https://github.com/geomarker-io/hamilton_property_code_enforcement/issues/2 is fixed, we shouldn't have problems using the latest version of `codec`

Also maybe related, but I am not seeing the "hh_acs_measures" data in the app when the box is checked.  Double check when updating codec version.

**Comment by andrew-vancil** [comment]
Found the bug to grab the "hh_acs_measures" data, so that should be good.

So when I went to update `codec`, devtools didn't find a newer version than I had. I did update `cincy`, though, but that seems to have broken the app. I'm now getting an error on `cincy::interpolate` about the geographies that we're interpolating _to_, so I'll look into that. Was there a recent change to `interpolate` or the `cincy` datasets?

**Comment by cole-brokamp** [comment]
I think that although we updated the version of the data source, we didn't update the code so that it would be included in codec: https://github.com/geomarker-io/codec/issues/82

Could the message be related to that?  Can you share the error message?  You could check for recent changes in the repositories or see if you have changed versions of the packages you are using to build the app?

**Comment by andrew-vancil** [comment]
I updated both cincy and codec to the most recent commits and nothing has changed. I'll open an issue on the `cincy` repo

**Comment by andrew-vancil** [comment]
I reverted and re-installed both `codec` and `cincy`, added in the property code enforcement data core and the explorer appears to be working as intended
